### ISSUE TITLE
Missing IP addresses

### ISSUE THREAD

**Issue by Multipartite** [thorchain/thornode-network#13]
At time of writing, my familiarity with this repository is low; I see for instance the below comment on IP address adding, but have not yet read through the code.

https://github.com/thorchain/thornode-network/blob/86d9c2948396a973aeda041fcc728c20d39b4a51/lambda%20functions/thormonitor_collect_data2/index.js#L1-L4

Currently there are many nodes shown in thornode.network with 'BAD' for BFR (Bifrost); taking the first as an example (.3s4y), the IP address is blank.

![another image](https://user-images.githubusercontent.com/100764240/192082034-4d7f0f9a-42de-4afb-a446-741cfc693fd2.png)

However, in ( https://thornode.ninerealms.com/thorchain/nodes ) .3s4y is shown as having IP address 34.97.164.139 .  
( http://34.97.164.139:6040/p2pid ) also returns Peer ID 16Uiu2HAm4Bkxy6vCjxEazXRSDe7wogZdwTv2roJYCTJgTXjJAGTu .

I submit this Issue with these observations in case someone more familiar with the code can perhaps go straight to the problem from it.  Thank you for your time.

**Comment by Thornode** [comment]
Code has been fixed.

**Comment by Multipartite** [comment]
Thank you very much!  I would like to learn how the code was changed, but do not see any new entries in 'Pull requests' (Closed or Open) or in ( https://github.com/thorchain/thornode-network/commits ); may I ask where this is displayed in GitHub?

**Comment by Thornode** [comment]
The code is maintained here (https://github.com/Thornode/thornode-network), then pulled to the official thorchain repo here.

The specific issue you are referring to is fixed by this extra lambda function 
https://github.com/Thornode/thornode-network/blob/main/lambda%20functions/thormonitor_update_ips/index.js

It runs every 10 mins and grabs the IP addresses and stores them to the DB. The initial problem is when the node first comes online when the data is collected there isn't always an IP to grab, and hence it gets saved to the DB with no IP and is not updated later. Hence this new lambda code to always check and update the IPs continuously.

**Comment by Multipartite** [comment]
Thank you very much for this information!
